# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               "Training on bioinformaics: RNA-Seq and Somatic-Seq"
tagline:             "Training on bioinformaics: RNA-Seq, Somatc-seq"
description:         NGS training
url:                 'https://bioinfo-dirty-jobs.github.io/master_course/'
baseurl:             '/master_course/'
twitter_username:
github_username:  bioinfo-dirty-jobs
pages_url: https://bioinfo-dirty-jobs.github.io/master_course
github_url: https://bioinfo-dirty-jobs.github.io/master_course

# Custom vars
version:             2.0

# Build settings
markdown: kramdown
